#!/usr/bin/env python3
"""Create WebP variants for explicitly listed theme assets; retain originals.

Run from the theme root. Requires Pillow. The source list is version-controlled;
never recursively converts unrelated artwork or downloadable documents.
"""
import json
import shutil
from pathlib import Path
from PIL import Image, ImageOps

root = Path(__file__).resolve().parents[1]
sources = json.loads((root / 'tools/seo-asset-sources.json').read_text())
manifest = []
lines = ['{%- comment -%}Generated by tools/optimize-storefront-assets.py.{%- endcomment -%}', '{%- case asset_name -%}']
for source in sources:
    path = root / 'assets' / source
    with Image.open(path) as original:
        im = ImageOps.exif_transpose(original).convert('RGBA' if 'A' in original.getbands() else 'RGB')
        width, height = im.size
        stem = 'sn-opt-' + path.stem
        variants = sorted(set([160, 320, 640, 960, 1280, width]))
        variants = [w for w in variants if w <= width]
        outputs = []
        for w in variants:
            target = root / 'assets' / f'{stem}-{w}.webp'
            resized = im if w == width else im.resize((w, max(1, round(height * w / width))), Image.Resampling.LANCZOS)
            if w == width and path.suffix.lower() == '.webp':
                shutil.copyfile(path, target)
            else:
                resized.save(target, 'WEBP', quality=86, method=6)
            outputs.append({'width': w, 'file': target.name, 'bytes': target.stat().st_size})
        # Delimited metadata keeps the image renderer small and shared by all callers.
        lines.append("  {%- when '" + source + "' -%}" + '|'.join([stem, str(width), str(height), ','.join(map(str,variants))]))
        manifest.append({'source': source, 'bytes_before': path.stat().st_size, 'width': width, 'height': height, 'variants': outputs})
lines.append('{%- endcase -%}')
(root / 'snippets/suntneew-asset-metadata.liquid').write_text('\n'.join(lines) + '\n')
output = root / 'output/seo-audit-20260908'
output.mkdir(parents=True, exist_ok=True)
(output / 'image-optimization.json').write_text(json.dumps(manifest, indent=2))
print(f'{len(manifest)} assets: {sum(m["bytes_before"] for m in manifest):,} original bytes -> {sum(m["variants"][-1]["bytes"] for m in manifest):,} full-resolution WebP bytes')
